### ISSUE TITLE
yelp_fieldlists

### ISSUE THREAD

**Issue by aftab740** [CAVIND46016/Yelp-Dataset-Analysis#1]
----> 7 from yelp_fieldlists import get_headers, get_data
      8 
      9 BUSINESS = "business"

ModuleNotFoundError: No module named 'yelp_fieldlists'

please solve it

**Comment by cavindsouza** [comment]
Have this script in the same dir as the json_to_csv file ==> **_https://github.com/CAVIND46016/Yelp-Dataset-Analysis/blob/master/yelp_fieldlists.py_**

**Comment by aftab740** [comment]
yes it is in same directory

**Comment by aftab740** [comment]
can u please share the latest .cvs file of yelp dataset

**Comment by aftab740** [comment]
ore send me the full detailed procedure of it how to convert it because i
lost my 3 days for the sake of this work. Thanks in advance

**Comment by CAVIND46016** [comment]
You can find them here and download it for free: 
_**https://www.yelp.com/dataset/download**_

**Comment by aftab740** [comment]
sir!
I have download all the .json files now i want to convert them in csv.
please guide me further. please see the aatached image of data set
[image: Capture.PNG]

**Comment by CAVIND46016** [comment]
Have all of the downloaded files and the two scripts as mentioned in one single directory. I assume those downloaded files are zipped (compressed) but don't have a file extension, so rename them by appending .zip or .rar at the end. You can now extract the actual csv files from the zip using winzip or winrar.

**Comment by aftab740** [comment]
i download the zip file i extract it. Then the extracted file extension is
changed with ".tar". then i extracted the file which i send you before.

**Comment by CAVIND46016** [comment]
Can you list the file_names extracted in the dir?? I did not receive the attachment, I couldn't open it.

**Comment by aftab740** [comment]
these files are  "business.json", "tip.json", "user.json", "review.json",
"chkin.json", "photo.json",
